flask_app/app/library/__init__.py
from flask import Blueprint

auth = Blueprint('auth', __name__)

from . import views

flask_app/app/library/views.py
from flask import render_template, redirect, request, url_for, flash 
from flask.ext.login import login_user
from . import auth
from ..models import User
from .forms import LoginForm, RegistrationForm
from flask.ext.login import logout_user, login_required
from .. import db


@auth.route('/login', methods=['GET', 'POST']) 
def login():
    form = LoginForm()
    if form.register.data:
        return redirect(url_for('auth.register'))
    if form.validate_on_submit():
        print 'validated!!!!!'
        user = User.query.filter_by(email=form.email.data).first()
        print 'user:'
        print user
        if user is not None and user.verify_password(form.password.data):
            print 'password verified!!!'
            login_user(user, form.remember_me.data)
            print 'logged in!!!!'
            #return redirect(request.args.get('next') 
            return render_template('library.html')
        flash('Invalid username or password.')
    return render_template('login.html', form=LoginForm())


@auth.route('/logout') 
@login_required
def logout():
    logout_user()
    flash('You have been logged out.') 
    return redirect(url_for('main.index'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    print 'accessed the register route'
    form = RegistrationForm()
    if form.validate_on_submit():
        print 'validated!!!!!!!!'
        user = User(email=form.email.data,
                    first_name = form.first_name.data,
                    password = form.password1.data)
        db.session.add(user)
        db.session.commit()
        flash('You can now login')
        return redirect(url_for('auth.login'))
    print form.errors
    return render_template('auth/register.html', form=form)
    

flask_app/app/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="row align-center" style='margin-top:200px'>
<container style="width:600px">
<p>
Hello, and welcome to Bookology.com
If you're sick and tired of the same stagnant book suggestions, and want to take control over the process, you've come to the right place.
Browse for books and rate books you've read to add them to your library. 
Go to the recommendations tab to mix and match the perfect combination of books and features to find your perfect next read!
</p>
</container>
</div>

{% endblock %}

flask_app/app/templates/base.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NextRead</title>
    
    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{ url_for('static', filename="css/foundation.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/app.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/styles.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/font-awesome.min.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/style.min.css") }}">
    <link rel="stylesheet" href="{{ url_for('static', filename="css/rating.min.css") }}">


  </head>
  
  <body background="https://upload.wikimedia.org/wikipedia/commons/2/2b/Bookshelf.jpg">

  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <div class="large-12 columns">
        <h1>NextRead</h1>
      </div>
    <ul class="menu">
      <li><a href="{{ url_for('main.search') }}">Browse for Books</a></li>
      <li><a href="{{ url_for('recommender.recommendations') }}">Get Recommendations</a></li>
      <li><a href="{{ url_for('main.library') }}">My Library</a></li>



      {% if current_user.is_authenticated %}
      <li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li> 
      {% else %}
      <li><a href="{{ url_for('auth.login') }}">Sign In</a></li> 
      {% endif %}
    </ul>

{% block content %}

{% endblock %}



    <script src= "{{ url_for('static', filename="js/vendor/jquery.js") }}"></script>
    <script src= "{{ url_for('static', filename="js/vendor/what-input.js") }}"></script>
    <script src= "{{ url_for('static', filename="js/vendor/foundation.js") }}"></script>
    <script src= "{{ url_for('static', filename="js/app.js") }}"></script>







    
  </body>
</html>

flask_app/app/templates/book_result.html
{% block content %}
<div class=book_id id = {{book_id}} style="padding-top:20px;"></div>
<div class="row" id="{{ 'iter' + n|string }}">
<div class=current_rating_div id={{ current_rating }}></div>
	
	<div class="small-2 columns", id={{web_id}}>
		<img class="search_result_cover" src="{{url_for('static', filename='book_covers/' + web_id|string + '.jpg')}}"/>
	</div>
	<div clas"shrink columns">
	    <div class="row">
	    	<h5>{{ title }}</h5>
	    </div>
	    <div class="row">
			 <div class="shrink columns">
				<h6 class="subheader">{{ author }}</h6>
			</div>
			<div class="shrink columns" id = {{web_id}}>
			 <div class="webId" id={{web_id}} style="display:none;" ></div>
			 <div class="initStatus" id="True" style="display:none;" ></div>

 				<div class="c-rating" id='c-rating' tag={{web_id}}>
				</div>
				<div class="shrink columns" id=clearRating>
				<div class=book_id id={{web_id}}></div>
			  	</div>

			</div>
		</div>
	</div>

</div>
{% endblock %}
 

flask_app/app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="row align-center">
  <div class="login-box">
    <form method="POST" action="">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="row align-center">
      {{form.email(placeholder="email")}}
       </div>
      <div class="row align-center">
      {{form.password(placeholder="password")}}
      </div>
      <div class="row align-left">
      {{form.submit_login(class="expanded button")}}
      </div>
      <div class="row align-center">
          {{form.register(class="expanded alert button")}}
      </div>
    </form>
</div>
</div>




{% endblock %}

flask_app/app/templates/library.html
{% extends "base.html" %}


{% block content %}
{{ super() }}
  
  <div class="row" style="padding-bottom: 30px; padding-top: 30px">
  	<h3>Hello {{current_user.name}}, welcome to your library!</h3>
<meta name="csrf-token" content="{{ csrf_token() }}">
   </div>
<div class=row>
  {% set n = 0 %}
  {% for book_read in current_user.books_read %}	
  {% set n = n+1 %}
  {% set book = db.session.query(Book).filter_by(id=book_read.book_id).first()%}
  	{% with author=book.author, title=book.title, web_id=book.web_id, n=n, current_rating=book_read.rating, book_id=book.id %}
      {% include 'library_book.html' %} 
  	{% endwith %}
 	{% endfor %}
 </div>


<script src= "{{ url_for('static', filename="js/vendor/rating.min.js") }}"></script>
<script src= "{{ url_for('static', filename="js/vendor/rating_script.js") }}"></script>

<script>


(function init() {
	var lastBookDiv = document.querySelectorAll(['.c-rating']);
	 	for (var i = 1; i < lastBookDiv.length+1; i++) {
		 	console.log('list item number:')
      var iter = i.toString()
      var iterId = 'iter'.concat(iter)
		 	var bookElem = document.getElementById(iterId);
      
      var webIdElem = bookElem.querySelector('.current_rating_div');
      current_rating = webIdElem.id 
	    addRatingWidget(bookElem, current_rating);
      }
})

();function sendBookData(rating, ratingElement, bookWebId, bookElem){
    	$.ajaxSetup({
            headers:
            { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
        });

    	    console.log(JSON.stringify({"rating": [[bookWebId], [rating]]}))
       $.ajax({

         type: "POST",
         contentType: "application/json; charset=utf-8",
         url: "{{ url_for('main.rating') }}",
         dataType: "json",
         async: true,
         data: JSON.stringify({"rating": [bookWebId, rating]}),   
         success: function (data) {
          addClearRating(bookElem, ratingElement)
         },
         error: function (result) {
         console.log('you messed up')
         }
       })
     }


function deleteReadRecord(book_id){
      $.ajaxSetup({
            headers:
            { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
        });

       $.ajax({

         type: "POST",
         contentType: "application/json; charset=utf-8",
         url: "{{ url_for('main.delete_read') }}",
         dataType: "json",
         async: true,
         data: JSON.stringify({"book_info": [book_id]}),   
         success: function (data) {
         },
         error: function (result) {
         console.log('you messed up')
         }
       })
     }

function removeBook(book_info){
  var book_id = book_info[0]
  var i = book_info[1]
  var iter = i.toString()
  var iterId = 'iter'.concat(iter)
  var BookElem = document.getElementById(iterId)
  deleteReadRecord(book_id)
  BookElem.parentNode.removeChild(BookElem)



}

     function clearRatingClick(ratingElement, bookElem, clearRatingElem){
                            	ratingElement.innerHTML='';
                            	addRatingWidget(bookElem, 0)
                            	clearRatingElem.parentNode.removeChild(clearRatingElem)}

     


    // ADD RATING WIDGET
    function addRatingWidget(bookElem, currentRating) {
    	
      console.log('function called');
      var ratingElement = bookElem.querySelector('.c-rating');
      console.log(bookElem)
      console.log(ratingElement);
      console.log(bookWebId)
      var bookWebId = ratingElement.parentNode.id;
      console.log(bookWebId);
      var maxRating = 5;
      var callback = function(rating, bookWebId, ratingElement) {
      	var ratingElement = bookElem.querySelector('.c-rating')
      	var bookWebId = ratingElement.querySelector('.webId').id
        deleteReadRecord(bookWebId);
      	sendBookData(rating, ratingElement, bookWebId, bookElem)
        }
      var r = rating(ratingElement, currentRating, maxRating, callback);  
    }
</script>
 
{% endblock %}






{% block scripts %}
{{ super() }}




{% endblock %}

flask_app/app/templates/library_book.html
{% block content %}


<div class="small-4 columns" id="{{ 'iter' + n|string }}" style="padding-bottom: 10px">
	<img class="library_book_cover" src="{{url_for('static', filename='book_covers/' + web_id|string + '.jpg')}}"/>
	<h6 style="width:130px">{{ title }}</h6>
	<h6 class="subheader" style="margin-top: -5px">{{ author }}</h6>
	<div class =current_rating_div id={{ current_rating }} style="display:none;"></div>
	<div class="c-rating" id='c-rating' style="margin-top: -7px">
		<div class="webId" id={{web_id}} style="display:none;" ></div>
	</div>
	<p class=removeBook onclick=removeBook([{{web_id}},{{n}}])>Remove from Library</p>
</div>





{% endblock %}

flask_app/app/templates/library_book_1.html
{% block content %}


<div class="shrink columns">
	<div class="row" >
		<div class="small-2 columns", id={{web_id}}>
			<img class="library_book_cover" src="/static/book_covers/{{ web_id }}.jpg"/>
		</div>
	</div>

	<div class="row">
		<div class="small-2 columns">
			<h6>{{ title }}</h6>
		</div>
	</div>
		
	<div class="row" id="{{ n }}">
		<div class="shrink columns">
			<h6 class="subheader">{{ author }}</h6>
		</div>
				
		<div class="shrink columns" id = {{web_id}}>
	 		<div class="c-rating" id='c-rating' tag={{web_id}}>
			</div>
		<div class="shrink columns" id=clearRating>
		</div>

		</div>
	</div>
	</div>



{% endblock %}

flask_app/app/templates/recommendations_book.html
{% block content %}


<div class="shrink columns" id="{{ 'iter' + n|string }}" style="padding-bottom:35px">
	<img class="recCover" id={{ web_id }} src="{{url_for('static', filename='book_covers/' + web_id|string + '.jpg')}}"/>
	<!--<div class =current_rating_div id={{ current_rating }}></div>
	<div class="c-rating" id='c-rating' style='padding-top:5px'></div>
	 <p class=removeBook onclick=removeBook([{{book_id}},{{n}}])>Remove from Library</p> -->
	</div>





{% endblock %}

flask_app/app/templates/recommendations_library_book.html
{% block content %}


<div class="small-4 columns" id="{{ n }}">
	<img class="library_book_cover" src="/static/book_covers/{{ web_id }}.jpg"/>
	<h6>{{ title }}</h6>
	<h6 class="subheader">{{ author }}</h6>
	<div class =current_rating_div id={{ current_rating }}></div>
	<div class="c-rating" id='c-rating'></div>
	<p class=removeBook onclick=removeBook([{{book_id}},{{n}}])>Remove from Library</p>
	</div>





{% endblock %}

flask_app/app/templates/search.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="/">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
</form>

<div class="row" style="padding-top:40px;">
	<h4>Add Books to your Library</h4>
</div>

<div class="row" >
	<form class="row" action="{{ url_for('main.search') }}" method="post" name="search" >
		<div class="shrink columns">
			{{ g.search_form.hidden_tag() }}{{ g.search_form.search(size=40, placeholder='enter title or author') }}
		</div>
		<div class="shrink columns" style="margin-left:-20px">
			<input type="submit" value="Search" class=button>
		</div>

	</form>

	<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

</div>


<div class="row", id="search_result">

</div>




{% endblock %}

flask_app/app/templates/search_results.html
{% extends "search.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
{{ super() }}

{% if results|length == 0 %}
<div class="alert callout" data-closable style=" max-width: 1000px; margin-left:auto; margin-right: auto;">
  <div class="row">
    <h5>Whoops! We couldn't find any results for your search. </h5>
  </div>
    <div class="row">
      <p>If you searched by title, try searching by author.</p>
  </div>
  <div class="row">
      <p>You can also combine author and title. For example: <i>"Harry Potter Rowling"</i></p>
  </div>
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

  
  <div class="row" style="padding-bottom: 30px; padding-top: 30px">
  	<h5>Search results for <i>"{{ query }}"</i>:</h5>
<meta name="csrf-token" content="{{ csrf_token() }}">
   </div>
<div class="row" style="margin-top:-30px; margin-bottom:15px">
<p style="font-size:16px;">Rate books you've read to add them to your library<p>
</div>


 <div id="books">
  {% set n = 0 %}
  {% for book in results %}	
  {% set n = n+1 %}
  {% if db.session.query(Read).filter_by(book_id=book.id, user_id=current_user.id).first() %}
  {% set current_rating = db.session.query(Read).filter_by(book_id=book.id, user_id=current_user.id).first().rating %}
  {% else %}
  {% set current_rating = 0 %}
  {% endif %}
  	{% with author=book.author, title=book.title, web_id=book.web_id, n=n, current_rating=current_rating, book_id=book.id %}
      {% include 'book_result.html' %} 
  	{% endwith %}
 	{% endfor %}
 </div>
<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src= "{{ url_for('static', filename="js/vendor/rating.min.js") }}"></script>
<script src= "{{ url_for('static', filename="js/vendor/rating_script.js") }}"></script>


<script>

function deleteReadRecord(book_id, calledBy){
      $.ajaxSetup({
            headers:
            { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
        });

       $.ajax({

         type: "POST",
         contentType: "application/json; charset=utf-8",
         url: "{{ url_for('main.delete_read') }}",
         dataType: "json",
         async: true,
         data: JSON.stringify({"book_info": [book_id]}),   
         success: function (data) {
         },
         error: function (result) {
         console.log('you messed up')
         }
       })
     }


(function init() {
	var lastBookDiv = document.querySelectorAll(['.c-rating']);
	 	for (var i = 1; i < lastBookDiv.length+1; i++) {
		 	      var iter = i.toString()
      var iterId = 'iter'.concat(iter)
      var bookElem = document.getElementById(iterId);
      
      var webIdElem = bookElem.querySelector('.current_rating_div');
		 	var current_rating = bookElem.querySelector('.current_rating_div').id
		 	      var ratingElement = bookElem.querySelector('.c-rating');

		 	if (current_rating != 0){ addClearRating(bookElem, ratingElement)

		 	}
	        addRatingWidget(bookElem, current_rating, ratingElement);
      }
})();


    function sendBookData(rating, ratingElement, bookWebId, bookElem, calledBy){
    	$.ajaxSetup({
            headers:
            { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
        });

    	    console.log(JSON.stringify({"rating": [[bookWebId], [rating]]}))
       $.ajax({

         type: "POST",
         contentType: "application/json; charset=utf-8",
         url: "{{ url_for('main.rating') }}",
         dataType: "json",
         async: true,
         data: JSON.stringify({"rating": [bookWebId, rating]}),   
         success: function (data) {
          var initStatus = bookElem.querySelector('.initStatus')
          initStatus.id= 'False'
          if (bookElem.querySelector('.clearRatingElem') == undefined){
            addClearRating(bookElem, ratingElement)
          };
         },
         error: function (result) {
         console.log('you messed up')
         }
       })
     }



     function addClearRating(bookElem, ratingElement){    	                            
     	var clearRatingElem = document.createElement("p")
     	clearRatingElem.className = 'clearRatingElem';
     	clearRatingElem.innerHTML = 'Remove from Library';
      var current_rating = bookElem.querySelector('.current_rating_div').id
     	var book_id = bookElem.querySelector('.book_id').id;
     	clearRatingElem.onclick = function () {
                            	ratingElement.innerHTML='';
                            	addRatingWidget(bookElem, 0, ratingElement)
                            	clearRatingElem.parentNode.removeChild(clearRatingElem)
                            	deleteReadRecord(book_id)
                            };
        
        ratingElement.parentNode.lastElementChild.appendChild(clearRatingElem)


     }

$(document).ready(function ()  {
  $(document).on('click',".c-rating", function ()  {
    var bookElem = this.parentNode.parentNode.parentNode.parentNode;
    var initStatus = bookElem.querySelector('.initStatus').id;
    var clearRatingElem = bookElem.querySelector('.clearRatingElem');
    var ratingElement = this
    var current_rating = bookElem.querySelector('.current_rating_div').id
    var bookWebId = bookElem.querySelector('.webId').id;
    //if (clearRatingElem !== undefined && initStatus == 'True'){
          //alert('c-rating clicked, clearRating was present')
          //deleteReadRecord(bookWebId, 1);
          //sendBookData(current_rating, ratingElement, bookWebId, bookElem, 1)

      //};
  })
})


    // ADD RATING WIDGET
    function addRatingWidget(bookElem, currentRating, ratingElement) {

      console.log('function called');
      var bookWebId = ratingElement.parentNode.id;
      var maxRating = 5;
      var callback = function(rating, bookWebId, ratingElement) {
        console.log(bookElem)
      	var ratingElement = bookElem.querySelector('.c-rating');
        var bookWebId = bookElem.querySelector('.webId').id;
        var initStatus = bookElem.querySelector('.initStatus').id;
        var clearRatingElem = bookElem.querySelector('.clearRatingElem')
        var current_rating = bookElem.querySelector('.current_rating_div')
        current_rating.id = rating

        if (clearRatingElem !== undefined && initStatus !== 'True'){
          deleteReadRecord(bookWebId, 2);
        
      };
      	sendBookData(rating, ratingElement, bookWebId, bookElem, 2)
      	 }
      var r = rating(ratingElement, currentRating, maxRating, callback);  
    }
</script>
 
{% endblock %}






{% block scripts %}
{{ super() }}




{% endblock %}